services:
  api:
    build: .
    env_file:
      - .env.production
    environment:
      - PORT=4242
      - FEIT_CODE_ENV=${FEIT_CODE_ENV}
      - DOCKER_HOST=tcp://dind:2375
    ports:
      - "4242:4242"
    depends_on:
      - dind

  dind:
    image: docker:19.03.12-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-storage:/var/lib/docker

volumes:
  dind-storage:
