services:
  api:
    build: .
    ports:
      - 4242:4242
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=${PORT}
      - FEIT_CODE_ENV=${FEIT_CODE_ENV}
      - CLERK_SECRET=${CLERK_SECRET}
      - DOCKER_HOST=unix:///var/run/docker.sock
